name: Build IfcOpenShell Linux

on:
  push:
    branches:
      - v0.8.0
  workflow_dispatch:

jobs:
  build_ifcopenshell:
    runs-on: ubuntu-20.04
    container: rockylinux:8

    steps:
      - name: Install Dependencies
        run: |
          yum update -y
          yum install -y gcc gcc-c++ git autoconf automake bison make zip cmake python3 \
                         bzip2 patch mesa-libGL-devel libffi-devel fontconfig-devel     \
                         sqlite-devel bzip2-devel zlib-devel openssl-devel xz-devel     \
                         readline-devel ncurses-devel libffi-devel libuuid-devel git-lfs findutils

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout Build Repository
        uses: actions/checkout@v3
        with:
          repository: aothms/build-outputs
          path: ./build
          ref: rockylinux8-x64
          lfs: true
          token: ${{ secrets.BUILD_REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Unpack Dependencies
        run: |
          find ./build -type f -name '*.tar.gz' -exec tar -xzf {} -C $(dirname {}) \;

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${GITHUB_WORKFLOW}-rockylinux8-x64

      - name: Run Build Script
        run: |
          CXXFLAGS="-O3" CFLAGS="-O3 ${DARWIN_C_SOURCE}" ADD_COMMIT_SHA=1 BUILD_CFG=Release python3 ./nix/build-all.py --diskcleanup --py-310

      - name: Pack Dependencies
        run: |
          cd build
          for install_dir in $(find $(find . -maxdepth 4 -name install) -mindepth 1 -maxdepth 1 -type d); do
            tar -czf "$install_dir.tar.gz" "$install_dir";
          done

      - name: Commit and Push Changes to Build Repository
        run: |
          cd build
          git config user.name "IfcOpenBot"
          git config user.email "ifcopenbot@ifcopenshell.org"
          git add "$(find . -maxdepth 4 -name install)/*.tar.gz"
          git commit -m "Update build artifacts [skip ci]" || echo "No changes to commit"
          git push
